# Rename this file to languages.toml to enable multilingual support
[zh-tw]
languageName = "繁體中文"
languagedirection = "ltr"
title = "Miya ㄉ網站"
weight = 1

[en]
languageName = "English"
languagedirection = "ltr"
title = "Miya's Blog"
weight = 2

[fr]
languageName = "Français"
languagedirection = "ltr"
title = "Le blog de Miya"
weight = 3
